add_subdirectory(main)
add_subdirectory(proj)
add_subdirectory(gdal)
add_subdirectory(raster)
if(SPATIAL_USE_GEOS)
  add_subdirectory(geos)
endif()
add_subdirectory(osm)
add_subdirectory(shapefile)
add_subdirectory(mvt)
add_subdirectory(wkb)

set(EXTENSION_SOURCES
    ${EXTENSION_SOURCES}
    PARENT_SCOPE)
