#!/usr/bin/env python3
"""Writes raster_examples.test from the examples in the documentation of the raster functions.

Run from the repository root after a build: python3 test/sql/raster/generate_examples_test.py [path/to/duckdb]

Every example is executed. An example that documents its result ("query", a line of four dashes, then the rows) must
produce exactly that result, otherwise the script fails and the documentation has to be fixed.
"""
import json
import re
import subprocess
import sys

DUCKDB = sys.argv[1] if len(sys.argv) > 1 else "./build/release/duckdb"
OUTPUT = "test/sql/raster/raster_examples.test"

FUNCTIONS = """
SELECT DISTINCT function_name, unnest(examples) AS example
FROM duckdb_functions()
WHERE list_contains(parameter_types, 'RASTER') OR list_contains(parameter_types, 'RASTER[]')
   OR return_type IN ('RASTER', 'RASTER[]') OR function_name IN ('ST_ReadRaster', 'ST_GDALDrivers')
ORDER BY function_name, example
"""


def run(sql, *flags):
    result = subprocess.run([DUCKDB, *flags, "-c", sql], capture_output=True, text=True)
    if result.returncode != 0:
        raise SystemExit("FAILED: %s\n%s" % (sql, result.stderr))
    return result.stdout


def rows_of(text):
    return [re.split(r"\t| {4}", line.rstrip()) for line in text.strip("\n").split("\n")]


def main():
    seen = set()
    blocks = []
    errors = []
    for entry in json.loads(run(FUNCTIONS, "-json")):
        example = entry["example"].strip()
        if not example:
            raise SystemExit("%s has no example" % entry["function_name"])
        if example in seen:
            continue
        seen.add(example)

        sql, _, documented = example.partition("\n----\n")
        sql = sql.strip().rstrip(";")
        actual = run(sql + ";", "-noheader", "-list", "-separator", "\t", "-nullvalue", "NULL").strip("\n")
        if documented and rows_of(documented) != rows_of(actual):
            errors.append("The documented result of %s is wrong.\n%s\nDocumented:\n%s\nActual:\n%s"
                          % (entry["function_name"], sql, documented, actual))
        columns = len(actual.split("\n")[0].split("\t"))
        blocks.append("# %s\nquery %s\n%s;\n----\n%s\n" % (entry["function_name"], "I" * columns, sql, actual))

    if errors:
        raise SystemExit("\n\n".join(errors))
    with open(OUTPUT, "w") as out:
        out.write("# name: %s\n# group: [raster]\n\n" % OUTPUT)
        out.write("# Generated by test/sql/raster/generate_examples_test.py: the examples of the raster function\n")
        out.write("# documentation, with the results they document\n\n")
        out.write("require spatial\n\n")
        out.write("\n".join(blocks))
    print("%d examples written to %s" % (len(blocks), OUTPUT))


if __name__ == "__main__":
    main()
